import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "./state/AppContext";
import {ClerkProvider} from "@clerk/nextjs"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`h-full antialiased`}
      >
        <body suppressHydrationWarning className="min-h-full flex flex-col">
          <main className="bg-input-bg min-h-screen">
            <AppProvider>
              {children}
            </AppProvider>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
