import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "./state/AppContext";
import Header from "./shared/ui/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <main className="bg-input-bg min-h-screen">
          <Header />
          <AppProvider>
            {children}
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
